
import http from 'http';

function doRequest(options, data) {
    return new Promise((resolve, reject) => {
        const req = http.request(options, (res) => {
            let body = '';
            res.on('data', (chunk) => body += chunk);
            res.on('end', () => {
                try {
                    resolve({ statusCode: res.statusCode, body: JSON.parse(body || '{}') });
                } catch (e) {
                    resolve({ statusCode: res.statusCode, body: body });
                }
            });
        });
        req.on('error', reject);
        if (data) req.write(JSON.stringify(data));
        req.end();
    });
}

async function verify() {
    console.log("Verifying fix...");

    // 1. Get Clientes to have a valid ID
    console.log("Fetching clients...");
    let clientId;
    try {
        const clientsRes = await doRequest({
            hostname: 'localhost',
            port: 3000,
            path: '/api/clientes',
            method: 'GET'
        });

        if (clientsRes.statusCode === 200 && Array.isArray(clientsRes.body) && clientsRes.body.length > 0) {
            clientId = clientsRes.body[0].id_cliente;
            console.log(`Using client ID: ${clientId}`);
        } else {
            console.log("Could not fetch clients or empty list. Using ID 1 as fallback.");
            clientId = 1;
        }
    } catch (e) {
        console.error("Could not connect to API (is server running?):", e.message);
        // Assuming server might be on another port or not running, but we try anyway?
        // If connection refused, we can't test.
        return;
    }


    // 2. Create Factura
    const payload = {
        numero_factura: 'TEST-' + Math.floor(Math.random() * 1000),
        fecha_factura: '2025-12-10',
        cliente_id: clientId,
        contrato_id: null,
        subtotal: 100,
        total: 100, // Matching subtotal as requested
        estado: 'PENDIENTE',
        notas: 'Test invoice generated by script',
        items: [{ descripcion: 'Test Service', cantidad: 1, precio_unitario: 100 }]
    };

    console.log("Sending invoice payload:", payload);
    try {
        const createRes = await doRequest({
            hostname: 'localhost',
            port: 3000,
            path: '/api/facturas',
            method: 'POST',
            headers: { 'Content-Type': 'application/json' }
        }, payload);

        if (createRes.statusCode >= 200 && createRes.statusCode < 300) {
            console.log("SUCCESS: Factura created successfully!");
            console.log("Response:", createRes.body);

            // 3. Verify GET
            console.log("Verifying GET /api/facturas...");
            const getRes = await doRequest({
                hostname: 'localhost',
                port: 3000,
                path: '/api/facturas',
                method: 'GET'
            });

            if (getRes.statusCode === 200 && Array.isArray(getRes.body)) {
                console.log(`SUCCESS: GET returned ${getRes.body.length} invoices.`);
                const last = getRes.body[0];
                if (last.id_contrato !== undefined) {
                    console.log("SUCCESS: Response contains 'id_contrato'.");
                } else {
                    console.log("WARNING: Response missing 'id_contrato'. keys:", Object.keys(last));
                }
            } else {
                console.error("FAILURE: GET failed with status", getRes.statusCode);
            }

        } else {
            console.error("FAILURE: Status code", createRes.statusCode);
            console.error("Response:", createRes.body);
        }
    } catch (e) {
        console.error("Request failed:", e.message);
    }
}

verify();
